### ISSUE TITLE
Media Library button to upload all images is broken

### ISSUE THREAD

**Issue by johndcoy** [jobthomas/gm2016#10]
The image uploader for all images is broken.
<img width="808" alt="screen shot 2016-09-19 at 12 04 54" src="https://cloud.githubusercontent.com/assets/2876178/18645268/5d119566-7e61-11e6-999a-44604db25d86.png">

**Comment by Luminus** [comment]
@jobthomas this has already been reported in #3

**Comment by jobthomas** [comment]
indeed @johndcoy @Luminus
